EducationDepartmentV1/Controllers/FlowChartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EducationDepartmentV1.Models;
using System.Web.Script.Serialization;
using Newtonsoft.Json.Linq;

namespace EducationDepartmentV1.Controllers
{
    public class FlowChartController : Controller
    {
        // GET: FlowChart
        //public ActionResult flowChartView()
        //{
        //    flowChart fc = new flowChart();
        //    return View();
        //}

        [HttpGet]
        public ActionResult FlowChart()
        {
            ViewBag.Message = "Video";

            return View();
        }


        [HttpPost]
        public JsonResult FlowChartFromJSON(int id)
        {
            ViewBag.Message = "Video";
            FlowChartContext flowChartContext = new FlowChartContext();
            flowChart fc = flowChartContext.flowCharts.Single(flow => flow.id == id);
            String s = fc.jsonDoc;
            System.Diagnostics.Debug.WriteLine(s);
            //var json = new JavaScriptSerializer();
            //var data = json.Deserialize<Dictionary<string, Dictionary<string, string>>[]>(s);
            
            JObject json = JObject.Parse(s);
            System.Diagnostics.Debug.WriteLine(json);
            return Json(s, JsonRequestBehavior.AllowGet);
            //return json;
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult FlowChart(flowChart requests)
        {
            if (requests == null)
            {
                System.Diagnostics.Debug.WriteLine("its null");
            }
            FlowChartContext flowChartContext = new FlowChartContext();
            flowChart fc = new flowChart();
            //fc.id  = requests.id;
            fc.jsonDoc = requests.jsonDoc;
            //Console.Write(requests.id);
            //Console.Write(requests.jsonDoc);
            System.Diagnostics.Debug.WriteLine(fc.id);
            System.Diagnostics.Debug.WriteLine(fc.jsonDoc);
            flowChartContext.flowCharts.Add(fc);
            flowChartContext.SaveChanges();
            System.Diagnostics.Debug.WriteLine("successfully added");
            ViewBag.Message = "Video";
            return View();
        }
    }
}

EducationDepartmentV1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title -Education Department</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
 @*   @Scripts.Render("~/bundles/rappid")*@

    <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css">

    <style>
        body {
            padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
        }
    </style>
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
                <div class="container">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="#">Education Department</a>
                    </div>

                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse" id="navbar">
                        <ul class="nav navbar-nav">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("Faculty", "Faculty","Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                            <li>@Html.ActionLink("Video Tutorials", "Video", "Home")</li>
                            
                        </ul>
                    </div><!-- end navbar-collapse -->
                </div><!-- end container-fluid -->
            </nav>

            <!-- 		<div class="row"> -->
            <!-- <div class="col-md-3"> -->
            <div id="sidebar-wrapper">
                <ul class="sidebar-nav">
                    <li class="sidebar-brand">
                        <a href="#">
                            Learning Task Analysis
                        </a>
                    </li>
                    <li>
                        <a href="#">What is task analysis ?</a>
                    </li>
                    <li>
                        <a href="~/trial/KitchenSink/index.html">How to conduct a task analysis</a>
                    </li>
                    <li>
                        @Html.ActionLink("Practice with examples", "PWE","Home")
                    </li>
                    <li>
                        @Html.ActionLink("Flow Chart", "FlowChart", "FlowChart")
                       @* <a href="#">Let’s work on your project</a>*@
                    </li>
                    <li>
                        @Html.ActionLink("Example Repository", "ExampleRepository", "Home")
                    </li>
                </ul>
            </div>
        </div>
</div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer class="row siteinfo">
            <p>Education Department offer you variety of courses. This site is awesome.</p>
        </footer>
    </div>

            @Scripts.Render("~/bundles/jquery")
            @Scripts.Render("~/bundles/bootstrap")
            @RenderSection("scripts", required: false)
</body>
</html>