EducationDepartmentV1/Controllers/ExampleController.cs
using EducationDepartmentV1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EducationDepartmentV1.Controllers
{
    public class ExampleController : Controller
    {
        // GET: Example
        [HttpGet]
        public ActionResult Example1()
        {
            return View();
        }

        public class CreateExampleRequests
        {
            public String id { get; set; }
            public String contetn { get; set; }
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Example1(CreateExampleRequests requests)
        {
            var example = new Example();
            //example.id = requests.id;
            example.contetn = requests.contetn;
            example.id = 1;
       //     example.lastDate = DateTime.Now;
            var db = new  ExamplDBContext();
           // db.Example.Attach(example);
           // db.Entry(example).State = System.Data.Entity.EntityState.Added;
             db.Example.Add(example);
            db.SaveChanges();

            //db.Example.Add(example);
            //db.SaveChanges();
            return View();
        }

        public ActionResult Example2()
        {
            return View();
        }

        public ActionResult Example3()
        {
            return View();
        }
    }
}

EducationDepartmentV1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EducationDepartmentV1.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult index()
        {
            return View();
        }

        public ActionResult Faculty()
        {
            ViewBag.Message = "Your Faculty page.";

            return View();
        }

        public ActionResult Contact()
        {
                ViewBag.Message = "Your contact page.";

                return View();
        }

        public ActionResult PWE()
        {
            ViewBag.Message = "Practice With Example";

            return View();
        }

        public ActionResult ExampleRepository()
        {
            ViewBag.Message = "Example Repository";

            return View();
        }

        public ActionResult Video()
        {
            ViewBag.Message = "Video";

            return View();
        }

        //public ActionResult FlowChart()
        //{
        //    ViewBag.Message = "Video";

        //    return View();
        //}

        //public ActionResult Example1()
        //{
        //    ViewBag.Message = "Video";

        //    return View();
        //}
    }
}

EducationDepartmentV1/Views/Home/Contact.cshtml
<!DOCTYPE html>

<html>
<body>
    <div class="container-fluid">
        <div class="row">
            </div>
    </div><!-- end container -->
    <!-- javascript -->
    <script>
        $("textarea").tooltip();
        $(".form-group.collapse").collapse();
    </script>
</body>
</html>

EducationDepartmentV1/Views/Home/ExampleRepository.cshtml
<!DOCTYPE html>
<html>
<body onload="myFunction()">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-9">
                <h2>Cognitive</h2>
                <table class="table table-bordered table-hover">
                    <thead>
                        <tr>
                            <th>Type</th>
                            <th>Name</th>
                            <th>Modified</th>
                            <th>Modified By</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td><i class="fa fa-file-text"></i></td>
                            <td>Moe</td>
                            <td><p id="demo"></p></td>
                            <td>random</td>
                        </tr>
                        <tr>
                            <td><i class="fa fa-file-pdf-o"></i></td>
                            <td>Moe</td>
                            <td><p id="demo"></p></td>
                            <td>random</td>
                        </tr>
                        <tr>
                            <td><i class="fa fa-file-powerpoint-o"></i></td>
                            <td>Moe</td>
                            <td><p id="demo"></p></td>
                            <td>random</td>
                        </tr>
                        <tr>
                            <td><i class="fa fa-file-excel-o"></i></td>
                            <td>Moe</td>
                            <td><p id="demo"></p></td>
                            <td>random</td>
                        </tr>
                        <tr>
                            <td><i class="fa fa-file-text"></i></td>
                            <td>Moe</td>
                            <td><p id="demo"></p></td>
                            <td>random</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div><!-- end container -->
    </div>
    <!-- javascript -->
    <script>
            $("textarea").tooltip();
            $(".form-group.collapse").collapse();
    </script>
    <script>
            function myFunction() {
                var x = new Date(document.lastModified);
                document.getElementById("demo").innerHTML = x;
            }
    </script>

</body>
</html>

EducationDepartmentV1/Views/Home/Faculty.cshtml
<!doctype html>
<html>
<body onload="myFunction()">
@*<body>*@
    <div class="container-fluid">
        <div class="row">
            <ul>
                <li class="thumbnail col-sm-3 col-xs-6">
                    <a href="#landon" data-toggle="modal"><img src="~/images/batman.jpg" alt="Batman" height="200" width="100"></a>
                    <div class="caption">
                        <h3>Batman</h3>
                        <p>The Dark Knight</p>
                        <p><a href="#landon" data-toggle="modal" class="btn btn-primary" role="button">Read more</a></p>
                    </div>
                </li>
                <li class="thumbnail col-sm-3 col-xs-6">
                    <a href="#forteau" data-toggle="modal">
                        <img src="/images/hulk.jpg" alt="Hulk" height="200" width="100">
                    </a>
                    <div class="caption">
                        <h3>Hulk</h3>
                        <p>The Smasher</p>
                        <p><a href="#forteau" data-toggle="modal" class="btn btn-primary" role="button">Read more</a></p>
                    </div>
                </li>
                <li class="thumbnail col-sm-3 col-xs-6">
                    <a href="#nuan" data-toggle="modal"><img src="/images/superman.jpg" alt="Superman" height="200" width="100"></a>
                    <div class="caption">
                        <h3>Superman</h3>
                        <p>Superman</p>
                        <p><a href="#nuan" data-toggle="modal" class="btn btn-primary" role="button">Read more</a></p>
                    </div>
                </li>
                <li class="thumbnail col-sm-3 col-xs-6">
                    <a href="#perfington" data-toggle="modal"><img src="/images/Black_Widow-Classic-iOS.png" alt="BlackWidow" height="200" width="100"></a>
                    <div class="caption">
                        <h3>Black Widow</h3>
                        <p>The Black Widow</p>
                        <p><a href="#perfington" data-toggle="modal" class="btn btn-primary" role="button">Read more</a></p>
                    </div>
                </li>
            </ul>
        </div>
    </div><!-- end container -->
    <!-- modal windows -->
    <div id="landon" class="modal fade" tabindex="-1">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close glyphicon glyphicon-remove" data-dismiss="modal"></button>
                    <h3 class="modal-title">Batman</h3>
                </div>
                <div class="modal-body">
                    <p><img src="images/batman.jpg" alt="Batman" height="100" width="100" class="img-responsive pull-left">Batmana Batmana Batmana BatmanaBatmana BatmanaBatmana BatmanaBatmana BatmanaBatmana BatmanaBatmana BatmanaBatmana BatmanaBatmana Batmana</p>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-primary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

    <div id="forteau" class="modal fade" tabindex="-1">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close glyphicon glyphicon-remove" data-dismiss="modal"></button>
                    <h3 class="modal-title">Hulk</h3>
                </div>
                <div class="modal-body">
                    <p><img src="images/hulk.jpg" alt="Hulk" height="100" width="100" class="img-responsive pull-right">Hulk HulkHulk HulkHulk HulkHulk HulkHulk HulkHulk HulkHulk HulkHulk HulkHulk HulkHulk HulkHulk Hulk</p>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-primary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

    <div id="nuan" class="modal fade" tabindex="-1">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close glyphicon glyphicon-remove" data-dismiss="modal"></button>
                    <h3 class="modal-title">Superman</h3>
                </div>
                <div class="modal-body">
                    <p><img src="images/superman.jpg" alt="Superman" height="100" width="100" class="img-responsive pull-left">Superman Superman Superman Superman Superman Superman </p>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-primary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

    <div id="perfington" class="modal fade" tabindex="-1">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close glyphicon glyphicon-remove" data-dismiss="modal"></button>
                    <h3 class="modal-title">Balck Widow</h3>
                </div>
                <div class="modal-body">
                    <p><img src="images/Black_Widow-Classic-iOS.png" alt="BlackWidow" height="100" width="100" class="img-responsive pull-right">BalckWidow BalckWidow BalckWidow BalckWidow BalckWidow BalckWidow BalckWidow BalckWidow BalckWidow BalckWidow BalckWidow BalckWidow </p>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-primary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>


    <!-- javascript -->
    <script src="js/jquery.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
</body>
</html>

EducationDepartmentV1/Views/Home/Index.cshtml
<!doctype html>
<html>
<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div id="locations" class="carousel slide" data-ride="carousel">
                    <ol class="carousel-indicators">
                        <li data-target="#locations" data-slide-to="0" class="active"></li>
                        <li data-target="#locations" data-slide-to="1"></li>
                        <li data-target="#locations" data-slide-to="2"></li>
                        <li data-target="#locations" data-slide-to="3"></li>
                    </ol>
                    <div class="carousel-inner">
                        <div class="item active">
                            <img src="~/images/image1.jpg" alt="" width="1200" height="300">
                        </div>
                        <div class="item">
                            <img src="~/images/image2.jpg" alt="" width="1200" height="300">
                        </div>
                        <div class="item">
                            <img src="~/images/image3.jpg" alt="" width="1200" height="300">
                        </div>
                    </div>
                    <a class="left carousel-control" href="#locations" data-slide="prev">
                        <span class="glyphicon glyphicon-chevron-left"></span>
                    </a>
                    <a class="right carousel-control" href="#locations" data-slide="next">
                        <span class="glyphicon glyphicon-chevron-right"></span>
                    </a>
                </div>
                <h2>What our students are saying...</h2>
                <blockquote>
                    <p>Some static content. Mission Statement Mission StatementMission StatementMission StatementMission StatementMission StatementMission StatementMission StatementMission StatementMission StatementMission StatementMission Statement</p>
                    <small>Anonymous Student, Education Department</small>
                </blockquote>
                <blockquote>
                    <p>Some static content. Mission Statement Mission StatementMission StatementMission StatementMission StatementMission StatementMission StatementMission StatementMission StatementMission StatementMission StatementMission Statement</p>
                    <small>Anonymous Student, Education Department</small>
                </blockquote>
            </div>
            <!-- </div> -->

            <footer class="row siteinfo">
                <p>Education Department offer you variety of courses. This site is awesome.</p>
            </footer>
        </div><!-- end container -->
</div>
        <!-- modal window -->
        <!-- javascript -->
        <script src="jquery.min.js"></script>
        <script src="bootstrap.min.js"></script>
        <script>
    	$('.carousel').carousel({
    		interval: 2000,
    		wrap: false
    	});
        </script>
</body>
</html>

EducationDepartmentV1/Views/Home/PWE.cshtml
<!DOCTYPE html>
<html>
<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-9">
                <table class="table table-bordered table-hover">
                    <thead>
                        <tr>
                            <th class="col-md-1">Example#</th>
                            <th class="col-md-1">Level</th>
                            <th class="col-md-3">Description</th>
                            <th class="col-md-1">CheckBox</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>@Html.ActionLink("Example1", "Example1", "Example")</td>
                            <td>Easy</td>
                            <td><p id="demo">Small Description</p></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td><a href="#">@Html.ActionLink("Example2", "Example2", "Example")</td>
                            <td>Medium</td>
                            <td><p id="demo">Small Description</p></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td><a href="#">@Html.ActionLink("Example3", "Example3", "Example")</td>
                            <td>Medium</td>
                            <td><p id="demo">Small Description</p></td>
                            <td></td>
                        </tr>
                    </tbody>
                </table>
            </div>

            <div class="col-md-3">
                <div class="row">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <h3>Additional Information</h3>
                        </div>
                        <div class="panel-body">
                            <p> Static content goes here static contetnt goes here Static content goes here static contetnt goes hereStatic content goes here static contetnt goes hereStatic content goes here static contetnt goes hereStatic content goes here static contetnt goes hereStatic content goes here static contetnt goes hereStatic content goes here static contetnt goes here </p>
                        </div>
                    </div><!-- end panel -->
                </div> <!--end row-->
            </div>
        </div>
    </div><!-- end container -->
    <!-- modal windows -->
    <div id="landon" class="modal fade" tabindex="-1">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close glyphicon glyphicon-remove" data-dismiss="modal"></button>
                    <h3 class="modal-title">Example 1</h3>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-xs-12">
                            <p class="lead text-center bg-info btn text-info center-block">Writing Learning Goals</p>
                            <div class="row">
                                <div class="col-xs-16 text-center">
                                    <p class="btn"><span class="glyphicon glyphicon-arrow-down"></span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12">
                            <p class="lead text-center bg-info btn text-info center-block">Writing Learning Goals</p>
                            <div class="row">
                                <div class="col-xs-16 text-center">
                                    <p class="btn"><span class="glyphicon glyphicon-arrow-down"></span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12">
                            <p class="lead text-center bg-info btn text-info center-block">Analyze types of learning outcomes</p>
                            <div class="row">
                                <div class="col-xs-16 text-center">
                                    <p class="btn"><span class="glyphicon glyphicon-arrow-down"></span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12">
                            <p class="lead text-center bg-info btn text-info center-block">Analyze information processing steps</p>
                            <div class="row">
                                <div class="col-xs-16 text-center">
                                    <p class="btn"><span class="glyphicon glyphicon-arrow-down"></span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="Insert Solution here">
                                <span class="input-group-btn">
                                    <button class="btn btn-default" type="button">Submit!</button>
                                </span>
                            </div><!-- /input-group -->
                        </div><!-- /.col-lg-6 -->
                    </div><!-- /.row -->
                    <div class="modal-footer">
                        <button class="btn btn-primary" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div id="landonExpert" class="modal fade" tabindex="-1">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close glyphicon glyphicon-remove" data-dismiss="modal"></button>
                    <h3 class="modal-title">Example 1</h3>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-xs-12">
                            <p class="lead text-center bg-info btn text-info center-block">Writing Learning Goals</p>
                            <div class="row">
                                <div class="col-xs-16 text-center">
                                    <p class="btn"><span class="glyphicon glyphicon-arrow-down"></span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12">
                            <p class="lead text-center bg-info btn text-info center-block">Writing Learning Goals</p>
                            <div class="row">
                                <div class="col-xs-16 text-center">
                                    <p class="btn"><span class="glyphicon glyphicon-arrow-down"></span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12">
                            <p class="lead text-center bg-info btn text-info center-block">Analyze types of learning outcomes</p>
                            <div class="row">
                                <div class="col-xs-16 text-center">
                                    <p class="btn"><span class="glyphicon glyphicon-arrow-down"></span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12">
                            <p class="lead text-center bg-info btn text-info center-block">Analyze information processing steps</p>
                            <div class="row">
                                <div class="col-xs-16 text-center">
                                    <p class="btn"><span class="glyphicon glyphicon-arrow-down"></span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12">
                            <p class="lead text-center bg-info btn text-info center-block">Correct Solution</p>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button class="btn btn-primary" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>
</body>
</html>

EducationDepartmentV1/Views/Home/Video.cshtml
<!DOCTYPE html>

<html>
<body onload="myFunction()">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-4">
                <iframe id="iframe_container" frameborder="0" webkitallowfullscreen="" mozallowfullscreen="" allowfullscreen="" align="middle" width="300" height="300" src="https://prezi.com/embed/ohbh9tlqkbqx/?bgcolor=ffffff&amp;lock_to_path=1&amp;autoplay=0&amp;autohide_ctrls=0&amp;landing_data=bHVZZmNaNDBIWWhJMmh5Rmt4enNSSHlZa0JXaGdFL1Z1T0pNWFRvZVpFb2J1RjlDRmEySy9EblhxN0dKa3dUYkZpZFNOTnY5ZWZHcXZNeWpiZXZJK2RoRlJ3PT0&amp;landing_sign=M6vCnRVB0rVLsFRy9OeKf4eaHM8zaywv2MbYqld_msg#"></iframe>
            </div>
            <div class="col-md-4">
                <iframe id="iframe_container" frameborder="0" webkitallowfullscreen="" mozallowfullscreen="" allowfullscreen="" align="middle" width="300" height="300" src="https://prezi.com/embed/ohbh9tlqkbqx/?bgcolor=ffffff&amp;lock_to_path=1&amp;autoplay=0&amp;autohide_ctrls=0&amp;landing_data=bHVZZmNaNDBIWWhJMmh5Rmt4enNSSHlZa0JXaGdFL1Z1T0pNWFRvZVpFb2J1RjlDRmEySy9EblhxN0dKa3dUYkZpZFNOTnY5ZWZHcXZNeWpiZXZJK2RoRlJ3PT0&amp;landing_sign=M6vCnRVB0rVLsFRy9OeKf4eaHM8zaywv2MbYqld_msg#"></iframe>
            </div>
            <div class="col-md-4">
                <iframe id="iframe_container" frameborder="0" webkitallowfullscreen="" mozallowfullscreen="" allowfullscreen="" align="middle" width="300" height="300" src="https://prezi.com/embed/ohbh9tlqkbqx/?bgcolor=ffffff&amp;lock_to_path=1&amp;autoplay=0&amp;autohide_ctrls=0&amp;landing_data=bHVZZmNaNDBIWWhJMmh5Rmt4enNSSHlZa0JXaGdFL1Z1T0pNWFRvZVpFb2J1RjlDRmEySy9EblhxN0dKa3dUYkZpZFNOTnY5ZWZHcXZNeWpiZXZJK2RoRlJ3PT0&amp;landing_sign=M6vCnRVB0rVLsFRy9OeKf4eaHM8zaywv2MbYqld_msg#"></iframe>
            </div>
            <div class="col-md-4">
                <iframe id="iframe_container" frameborder="0" webkitallowfullscreen="" mozallowfullscreen="" allowfullscreen="" align="middle" width="300" height="300" src="https://prezi.com/embed/ohbh9tlqkbqx/?bgcolor=ffffff&amp;lock_to_path=1&amp;autoplay=0&amp;autohide_ctrls=0&amp;landing_data=bHVZZmNaNDBIWWhJMmh5Rmt4enNSSHlZa0JXaGdFL1Z1T0pNWFRvZVpFb2J1RjlDRmEySy9EblhxN0dKa3dUYkZpZFNOTnY5ZWZHcXZNeWpiZXZJK2RoRlJ3PT0&amp;landing_sign=M6vCnRVB0rVLsFRy9OeKf4eaHM8zaywv2MbYqld_msg#"></iframe>
            </div>
            <div class="col-md-4">
                <iframe id="iframe_container" frameborder="0" webkitallowfullscreen="" mozallowfullscreen="" allowfullscreen="" align="middle" width="300" height="300" src="https://prezi.com/embed/ohbh9tlqkbqx/?bgcolor=ffffff&amp;lock_to_path=1&amp;autoplay=0&amp;autohide_ctrls=0&amp;landing_data=bHVZZmNaNDBIWWhJMmh5Rmt4enNSSHlZa0JXaGdFL1Z1T0pNWFRvZVpFb2J1RjlDRmEySy9EblhxN0dKa3dUYkZpZFNOTnY5ZWZHcXZNeWpiZXZJK2RoRlJ3PT0&amp;landing_sign=M6vCnRVB0rVLsFRy9OeKf4eaHM8zaywv2MbYqld_msg#"></iframe>
            </div>
            <div class="col-md-4">
                <iframe id="iframe_container" frameborder="0" webkitallowfullscreen="" mozallowfullscreen="" allowfullscreen="" align="middle" width="300" height="300" src="https://prezi.com/embed/ohbh9tlqkbqx/?bgcolor=ffffff&amp;lock_to_path=1&amp;autoplay=0&amp;autohide_ctrls=0&amp;landing_data=bHVZZmNaNDBIWWhJMmh5Rmt4enNSSHlZa0JXaGdFL1Z1T0pNWFRvZVpFb2J1RjlDRmEySy9EblhxN0dKa3dUYkZpZFNOTnY5ZWZHcXZNeWpiZXZJK2RoRlJ3PT0&amp;landing_sign=M6vCnRVB0rVLsFRy9OeKf4eaHM8zaywv2MbYqld_msg#"></iframe>
            </div>
        </div>
    </div><!-- end container -->
    <!-- javascript -->
    <script src="js/jquery.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script>
        $("textarea").tooltip();
        $(".form-group.collapse").collapse();
    </script>

</body>
</html>